### ISSUE TITLE
Is there any way I could contact you?

### ISSUE THREAD

**Issue by l3lackShark** [Andoryuuta/kiwi#10]
I have a problem with huge memory leaks on Linux, possibly related to your functions regarding memory reading. I would like to share the code with you, but I don't want to release it in public yet.

**Comment by Andoryuuta** [comment]
You can contact me at `andrew.gutekanst` `@` `gmail.com`  for kiwi-related issues you would like to keep private.

The public issue tracker is preferred however.

**Comment by l3lackShark** [comment]
Thanks, I'll write that down. The problem was actually on my side and I managed to resolve it.
